// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/opaque.dart';
import 'api/pairing.dart';
import 'api/simple.dart';
import 'api/vault_key.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  OpaqueClientStart dco_decode_opaque_client_start(dynamic raw);

  @protected
  OpaqueLoginFinish dco_decode_opaque_login_finish(dynamic raw);

  @protected
  OpaqueRegisterFinish dco_decode_opaque_register_finish(dynamic raw);

  @protected
  PairingOpened dco_decode_pairing_opened(dynamic raw);

  @protected
  PairingSealed dco_decode_pairing_sealed(dynamic raw);

  @protected
  PairingStart dco_decode_pairing_start(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  OpaqueClientStart sse_decode_opaque_client_start(
    SseDeserializer deserializer,
  );

  @protected
  OpaqueLoginFinish sse_decode_opaque_login_finish(
    SseDeserializer deserializer,
  );

  @protected
  OpaqueRegisterFinish sse_decode_opaque_register_finish(
    SseDeserializer deserializer,
  );

  @protected
  PairingOpened sse_decode_pairing_opened(SseDeserializer deserializer);

  @protected
  PairingSealed sse_decode_pairing_sealed(SseDeserializer deserializer);

  @protected
  PairingStart sse_decode_pairing_start(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_client_start(
    OpaqueClientStart self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_login_finish(
    OpaqueLoginFinish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opaque_register_finish(
    OpaqueRegisterFinish self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pairing_opened(PairingOpened self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_sealed(PairingSealed self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_start(PairingStart self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
