// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_doc`, `encode_doc`, `to_id16`

/// `VaultDoc` vide, encodé.
Uint8List crdtNew() => RustLib.instance.api.crateApiCrdtCrdtNew();

/// Marque une entrée présente (add-wins). Renvoie le doc + le delta.
CrdtMutation crdtAddEntry({
  required List<int> doc,
  required List<int> entryId,
  required List<int> deviceId,
}) => RustLib.instance.api.crateApiCrdtCrdtAddEntry(
  doc: doc,
  entryId: entryId,
  deviceId: deviceId,
);

/// Retire une entrée. Renvoie le doc + le delta.
CrdtMutation crdtRemoveEntry({
  required List<int> doc,
  required List<int> entryId,
}) => RustLib.instance.api.crateApiCrdtCrdtRemoveEntry(
  doc: doc,
  entryId: entryId,
);

/// Écrit un champ (LWW). `value` = `Ciphertext` encodé (opaque) ; le timestamp
/// `(wall_ms, counter)` est fourni par l'appelant (source d'horloge côté Dart).
/// Renvoie le doc + le delta.
CrdtMutation crdtSetField({
  required List<int> doc,
  required List<int> entryId,
  required int fieldId,
  required List<int> value,
  required BigInt wallMs,
  required int counter,
  required List<int> deviceId,
}) => RustLib.instance.api.crateApiCrdtCrdtSetField(
  doc: doc,
  entryId: entryId,
  fieldId: fieldId,
  value: value,
  wallMs: wallMs,
  counter: counter,
  deviceId: deviceId,
);

/// Fusionne un delta (ou un état complet — snapshot). Idempotent / commutatif.
/// Renvoie le doc résultant.
Uint8List crdtMerge({required List<int> doc, required List<int> delta}) =>
    RustLib.instance.api.crateApiCrdtCrdtMerge(doc: doc, delta: delta);

/// Identifiants (16 octets) des entrées **présentes**.
List<Uint8List> crdtEntryIds({required List<int> doc}) =>
    RustLib.instance.api.crateApiCrdtCrdtEntryIds(doc: doc);

/// Champs d'une entrée : `(field_id, Ciphertext encodé)`, pour la projection locale.
List<CrdtField> crdtEntryFields({
  required List<int> doc,
  required List<int> entryId,
}) => RustLib.instance.api.crateApiCrdtCrdtEntryFields(
  doc: doc,
  entryId: entryId,
);

/// `DeviceId` (16 o) dérivé de la clé publique d'appareil **Ed25519** (32 o) : ses 16
/// premiers octets. Unique et stable par appareil (128 bits d'une clé aléatoire) —
/// suffit au tiebreak HLC du CRDT.
Uint8List crdtDeviceIdFromKey({required List<int> publicKey}) =>
    RustLib.instance.api.crateApiCrdtCrdtDeviceIdFromKey(publicKey: publicKey);

/// Génère un `EntryId` aléatoire (16 o) via le CSPRNG de l'OS — pour une nouvelle
/// entrée du coffre.
Uint8List crdtNewEntryId() => RustLib.instance.api.crateApiCrdtCrdtNewEntryId();

/// Chiffre la valeur d'un champ (clé propre à l'entrée, dérivée de `vault_key` et
/// `entry_id`). Sortie = `Ciphertext` **encodé**, à passer à [`crdt_set_field`].
Uint8List crdtEncryptField({
  required List<int> vaultKey,
  required List<int> entryId,
  required List<int> plaintext,
}) => RustLib.instance.api.crateApiCrdtCrdtEncryptField(
  vaultKey: vaultKey,
  entryId: entryId,
  plaintext: plaintext,
);

/// Déchiffre la valeur d'un champ (issue de [`crdt_entry_fields`]) → clair.
Uint8List crdtDecryptField({
  required List<int> vaultKey,
  required List<int> entryId,
  required List<int> value,
}) => RustLib.instance.api.crateApiCrdtCrdtDecryptField(
  vaultKey: vaultKey,
  entryId: entryId,
  value: value,
);

/// Plus grand HLC du doc (tous les registres, présents ou tombstonés) →
/// `(wall_ms, counter)` ; `(0, 0)` si aucun champ n'a été écrit.
///
/// Après un merge distant, Dart avance son horloge locale au-delà de cette
/// valeur (via [`crdt_hlc_tick`] au prochain write) : sinon une écriture locale
/// estampillée d'un HLC inférieur à une valeur distante déjà fusionnée la
/// perdrait en LWW.
HlcTick crdtMaxHlc({required List<int> doc}) =>
    RustLib.instance.api.crateApiCrdtCrdtMaxHlc(doc: doc);

/// Fait avancer l'horloge HLC locale : renvoie le prochain `(wall_ms, counter)`
/// strictement supérieur, à persister par Dart et à passer à [`crdt_set_field`].
HlcTick crdtHlcTick({
  required BigInt lastWallMs,
  required int lastCounter,
  required BigInt nowMs,
}) => RustLib.instance.api.crateApiCrdtCrdtHlcTick(
  lastWallMs: lastWallMs,
  lastCounter: lastCounter,
  nowMs: nowMs,
);

/// Un champ énuméré : identifiant + valeur (`Ciphertext` encodé, opaque).
class CrdtField {
  final int fieldId;
  final Uint8List value;

  const CrdtField({required this.fieldId, required this.value});

  @override
  int get hashCode => fieldId.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrdtField &&
          runtimeType == other.runtimeType &&
          fieldId == other.fieldId &&
          value == other.value;
}

/// Un `VaultDoc` ré-encodé + le delta produit par une mutation.
class CrdtMutation {
  /// VaultDoc complet ré-encodé (à persister — source de vérité locale).
  final Uint8List doc;

  /// Delta à propager au serveur.
  final Uint8List delta;

  const CrdtMutation({required this.doc, required this.delta});

  @override
  int get hashCode => doc.hashCode ^ delta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrdtMutation &&
          runtimeType == other.runtimeType &&
          doc == other.doc &&
          delta == other.delta;
}

/// État d'horloge HLC d'un appareil, threadé par Dart (pas d'`HlcClock` vivant).
class HlcTick {
  final BigInt wallMs;
  final int counter;

  const HlcTick({required this.wallMs, required this.counter});

  @override
  int get hashCode => wallMs.hashCode ^ counter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HlcTick &&
          runtimeType == other.runtimeType &&
          wallMs == other.wallMs &&
          counter == other.counter;
}
