// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Génère la paire de clés d'identité de cet appareil.
DeviceKeypair deviceGenerateKeypair() =>
    RustLib.instance.api.crateApiDeviceKeyDeviceGenerateKeypair();

/// Signe un défi (nonce serveur) avec la graine secrète de cet appareil.
Uint8List deviceSignChallenge({
  required List<int> secret,
  required List<int> challenge,
}) => RustLib.instance.api.crateApiDeviceKeyDeviceSignChallenge(
  secret: secret,
  challenge: challenge,
);

/// Paire de clés d'identité d'appareil.
class DeviceKeypair {
  /// Clé publique (32 o) — placée dans le QR puis inscrite au registre du compte.
  final Uint8List public;

  /// Graine secrète (32 o) — à persister en secure storage, jamais transmise.
  final Uint8List secret;

  const DeviceKeypair({required this.public, required this.secret});

  @override
  int get hashCode => public.hashCode ^ secret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceKeypair &&
          runtimeType == other.runtimeType &&
          public == other.public &&
          secret == other.secret;
}
