// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Démarre l'enregistrement OPAQUE à partir du mot de passe maître.
Future<OpaqueClientStart> opaqueRegisterStart({required String password}) =>
    RustLib.instance.api.crateApiOpaqueOpaqueRegisterStart(password: password);

/// Finalise l'enregistrement à partir de la réponse du serveur.
Future<OpaqueRegisterFinish> opaqueRegisterFinish({
  required List<int> state,
  required String password,
  required List<int> response,
}) => RustLib.instance.api.crateApiOpaqueOpaqueRegisterFinish(
  state: state,
  password: password,
  response: response,
);

/// Démarre la connexion OPAQUE à partir du mot de passe maître.
Future<OpaqueClientStart> opaqueLoginStart({required String password}) =>
    RustLib.instance.api.crateApiOpaqueOpaqueLoginStart(password: password);

/// Finalise la connexion. **Échoue si le mot de passe est faux.**
Future<OpaqueLoginFinish> opaqueLoginFinish({
  required List<int> state,
  required String password,
  required List<int> response,
}) => RustLib.instance.api.crateApiOpaqueOpaqueLoginFinish(
  state: state,
  password: password,
  response: response,
);

/// Résultat d'un `*_start` client : état à conserver + message pour le serveur.
class OpaqueClientStart {
  /// État opaque à conserver côté client jusqu'au `finish`.
  final Uint8List state;

  /// Message à envoyer au serveur.
  final Uint8List message;

  const OpaqueClientStart({required this.state, required this.message});

  @override
  int get hashCode => state.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpaqueClientStart &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message;
}

/// Résultat de la finalisation de connexion.
class OpaqueLoginFinish {
  /// `CredentialFinalization` à envoyer au serveur.
  final Uint8List finalization;

  /// Clé de session mutuelle.
  final Uint8List sessionKey;

  /// Clé exportée (côté client, stable).
  final Uint8List exportKey;

  const OpaqueLoginFinish({
    required this.finalization,
    required this.sessionKey,
    required this.exportKey,
  });

  @override
  int get hashCode =>
      finalization.hashCode ^ sessionKey.hashCode ^ exportKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpaqueLoginFinish &&
          runtimeType == other.runtimeType &&
          finalization == other.finalization &&
          sessionKey == other.sessionKey &&
          exportKey == other.exportKey;
}

/// Résultat de la finalisation d'enregistrement.
class OpaqueRegisterFinish {
  /// `RegistrationUpload` à envoyer au serveur.
  final Uint8List upload;

  /// Clé exportée (côté client, stable).
  final Uint8List exportKey;

  const OpaqueRegisterFinish({required this.upload, required this.exportKey});

  @override
  int get hashCode => upload.hashCode ^ exportKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpaqueRegisterFinish &&
          runtimeType == other.runtimeType &&
          upload == other.upload &&
          exportKey == other.exportKey;
}
