// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// **Nouvel appareil** — démarre le pairing (paire éphémère X25519 + payload QR), en
/// incorporant sa clé d'identité `device_public_key` au QR et à l'état.
PairingStart pairingNewDeviceStart({required List<int> devicePublicKey}) =>
    RustLib.instance.api.crateApiPairingPairingNewDeviceStart(
      devicePublicKey: devicePublicKey,
    );

/// **Appareil source, tour 1** — scanne le QR et dérive le SAS. Ne publie que sa clé
/// publique : **aucun secret ne circule** tant que le SAS n'est pas confirmé.
PairingSourceBegin pairingSourceBeginRound({required List<int> qr}) =>
    RustLib.instance.api.crateApiPairingPairingSourceBeginRound(qr: qr);

/// **Nouvel appareil, tour 1** — reçoit la clé publique de la source et dérive le SAS
/// à comparer.
PairingConfirm pairingNewDeviceConfirmRound({
  required List<int> state,
  required List<int> hello,
}) => RustLib.instance.api.crateApiPairingPairingNewDeviceConfirmRound(
  state: state,
  hello: hello,
);

/// **Appareil source, tour 2** — scelle `{account_id, vault_key}`.
///
/// À n'appeler qu'**après** confirmation du SAS par l'utilisateur : c'est ce qui
/// empêche un MITM d'obtenir la VaultKey.
Uint8List pairingSourceSealRound({
  required List<int> state,
  required List<int> accountId,
  required List<int> vaultKey,
}) => RustLib.instance.api.crateApiPairingPairingSourceSealRound(
  state: state,
  accountId: accountId,
  vaultKey: vaultKey,
);

/// **Nouvel appareil, tour 2** — ouvre le blob scellé → VaultKey + account_id.
/// **Échoue** si le blob ne s'ouvre pas (mauvais destinataire / altération).
PairingOpened pairingNewDeviceOpen({
  required List<int> state,
  required List<int> sealed,
}) => RustLib.instance.api.crateApiPairingPairingNewDeviceOpen(
  state: state,
  sealed: sealed,
);

/// Résultat du **tour 1** côté nouvel appareil.
class PairingConfirm {
  /// État à conserver jusqu'à l'ouverture (contient la clé AEAD dérivée).
  final Uint8List state;

  /// SAS à afficher (doit correspondre à celui de la source).
  final String sas;

  const PairingConfirm({required this.state, required this.sas});

  @override
  int get hashCode => state.hashCode ^ sas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingConfirm &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          sas == other.sas;
}

/// Résultat de l'ouverture (**tour 2**) côté nouvel appareil.
class PairingOpened {
  /// VaultKey reçue (octets).
  final Uint8List vaultKey;

  /// Identifiant du compte que le nouvel appareil rejoint.
  final Uint8List accountId;

  const PairingOpened({required this.vaultKey, required this.accountId});

  @override
  int get hashCode => vaultKey.hashCode ^ accountId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingOpened &&
          runtimeType == other.runtimeType &&
          vaultKey == other.vaultKey &&
          accountId == other.accountId;
}

/// Résultat du **tour 1** côté appareil source.
class PairingSourceBegin {
  /// État à conserver jusqu'au scellage (contient la clé AEAD dérivée).
  final Uint8List state;

  /// Tour 1 à déposer au relais : la clé publique éphémère seule (aucun secret).
  final Uint8List hello;

  /// SAS à afficher. **Ne sceller qu'après** confirmation par l'utilisateur.
  final String sas;

  /// Clé d'identité du nouvel appareil, extraite du QR (liée au transcript). À
  /// inscrire au registre **uniquement après** confirmation du SAS.
  final Uint8List devicePublicKey;

  const PairingSourceBegin({
    required this.state,
    required this.hello,
    required this.sas,
    required this.devicePublicKey,
  });

  @override
  int get hashCode =>
      state.hashCode ^ hello.hashCode ^ sas.hashCode ^ devicePublicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingSourceBegin &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          hello == other.hello &&
          sas == other.sas &&
          devicePublicKey == other.devicePublicKey;
}

/// Résultat du démarrage côté **nouvel appareil**.
class PairingStart {
  /// État à conserver (contient le secret éphémère) jusqu'au tour 1.
  final Uint8List state;

  /// Payload QR du cœur (à envelopper côté Dart puis afficher).
  final Uint8List qr;

  const PairingStart({required this.state, required this.qr});

  @override
  int get hashCode => state.hashCode ^ qr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingStart &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          qr == other.qr;
}
