// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// **Nouvel appareil** — démarre le pairing (paire éphémère X25519 + payload QR).
PairingStart pairingNewDeviceStart() =>
    RustLib.instance.api.crateApiPairingPairingNewDeviceStart();

/// **Appareil source** — scelle la VaultKey vers le nouvel appareil décrit par le QR.
/// Renvoie la réponse à déposer + le SAS à afficher.
PairingSealed pairingSourceSeal({
  required List<int> qr,
  required List<int> vaultKey,
}) => RustLib.instance.api.crateApiPairingPairingSourceSeal(
  qr: qr,
  vaultKey: vaultKey,
);

/// **Nouvel appareil** — ouvre la réponse scellée → VaultKey + SAS. **Échoue** si le
/// blob ne s'ouvre pas (mauvais destinataire / altération).
PairingOpened pairingNewDeviceOpen({
  required List<int> state,
  required List<int> response,
}) => RustLib.instance.api.crateApiPairingPairingNewDeviceOpen(
  state: state,
  response: response,
);

/// Résultat de l'ouverture côté **nouvel appareil**.
class PairingOpened {
  /// VaultKey reçue (octets).
  final Uint8List vaultKey;

  /// SAS à afficher (doit correspondre à celui de la source).
  final String sas;

  const PairingOpened({required this.vaultKey, required this.sas});

  @override
  int get hashCode => vaultKey.hashCode ^ sas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingOpened &&
          runtimeType == other.runtimeType &&
          vaultKey == other.vaultKey &&
          sas == other.sas;
}

/// Résultat du scellage côté **appareil source**.
class PairingSealed {
  /// Réponse scellée à déposer au relais.
  final Uint8List response;

  /// SAS à afficher (doit correspondre à celui du nouvel appareil).
  final String sas;

  const PairingSealed({required this.response, required this.sas});

  @override
  int get hashCode => response.hashCode ^ sas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingSealed &&
          runtimeType == other.runtimeType &&
          response == other.response &&
          sas == other.sas;
}

/// Résultat du démarrage côté **nouvel appareil**.
class PairingStart {
  /// État à conserver (contient le secret éphémère) jusqu'à la réception.
  final Uint8List state;

  /// Payload QR du cœur (à envelopper côté Dart puis afficher).
  final Uint8List qr;

  const PairingStart({required this.state, required this.qr});

  @override
  int get hashCode => state.hashCode ^ qr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingStart &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          qr == other.qr;
}
