// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Version du cœur `realm-guard-core`, exposée via FFI.
/// Sert de point de validation de l'intégration Rust ↔ Flutter (P0.5).
String coreVersion() => RustLib.instance.api.crateApiSimpleCoreVersion();
