// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Enrobe la VaultKey (déjà enrobée par la KEK) sous la clé exportée OPAQUE.
///
/// `wrapped_vault_key` = état local (VaultKey enrobée par la KEK). Renvoie le blob
/// sérialisé à téléverser au serveur (`PUT /vault/key`).
Uint8List sealVaultKey({
  required List<int> exportKey,
  required List<int> wrappedVaultKey,
}) => RustLib.instance.api.crateApiVaultKeySealVaultKey(
  exportKey: exportKey,
  wrappedVaultKey: wrappedVaultKey,
);

/// Désenrobe le blob serveur avec la clé exportée OPAQUE.
///
/// `sealed` = blob récupéré du serveur (`GET /vault/key`). Renvoie la VaultKey
/// enrobée par la KEK (état local). **Échoue** si l'`export_key` ne correspond pas
/// (mauvais mot de passe re-dérivé) ou si le blob a été altéré.
Uint8List openVaultKey({
  required List<int> exportKey,
  required List<int> sealed,
}) => RustLib.instance.api.crateApiVaultKeyOpenVaultKey(
  exportKey: exportKey,
  sealed: sealed,
);
