// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Enrobe la VaultKey (déjà enrobée par la KEK) sous la clé exportée OPAQUE.
///
/// `wrapped_vault_key` = état local (VaultKey enrobée par la KEK). Renvoie le blob
/// sérialisé à téléverser au serveur (`PUT /vault/key`).
Uint8List sealVaultKey({
  required List<int> exportKey,
  required List<int> wrappedVaultKey,
}) => RustLib.instance.api.crateApiVaultKeySealVaultKey(
  exportKey: exportKey,
  wrappedVaultKey: wrappedVaultKey,
);

/// Désenrobe le blob serveur avec la clé exportée OPAQUE.
///
/// `sealed` = blob récupéré du serveur (`GET /vault/key`). Renvoie la VaultKey
/// enrobée par la KEK (état local). **Échoue** si l'`export_key` ne correspond pas
/// (mauvais mot de passe re-dérivé) ou si le blob a été altéré.
Uint8List openVaultKey({
  required List<int> exportKey,
  required List<int> sealed,
}) => RustLib.instance.api.crateApiVaultKeyOpenVaultKey(
  exportKey: exportKey,
  sealed: sealed,
);

/// Génère une **VaultKey** aléatoire (32 octets) — la clé racine du coffre local.
Uint8List generateVaultKey() =>
    RustLib.instance.api.crateApiVaultKeyGenerateVaultKey();

/// Enrobe la VaultKey sous la **KEK** (dérivée du mot de passe maître) pour le
/// stockage **local**. Renvoie le blob sérialisé (postcard).
Uint8List wrapVaultKey({required List<int> kek, required List<int> vaultKey}) =>
    RustLib.instance.api.crateApiVaultKeyWrapVaultKey(
      kek: kek,
      vaultKey: vaultKey,
    );

/// Désenrobe la VaultKey locale avec la KEK. **Échoue** si la KEK est fausse
/// (mauvais mot de passe) ou si le blob a été altéré.
Uint8List unwrapVaultKey({
  required List<int> kek,
  required List<int> wrapped,
}) => RustLib.instance.api.crateApiVaultKeyUnwrapVaultKey(
  kek: kek,
  wrapped: wrapped,
);
